# Generated by Django 5.1.4 on 2025-01-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Данные о зарплате',
                'verbose_name_plural': 'Данные о зарплатах',
                'ordering': ['-year'],
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
